#!/usr/bin/env bash
set -e

function help() {
    cat <<EOF
Edit files in place. Useful for changing strings in binaries on block
devices (my original use case).
Searches for 'search_string' and uses dd to copy 'replacement_string'
to specified position. Make sure string lengths are equal (often you
can either pad with spaces or use a terminating NUL character).

usage:
  `basename ${0}` search_string replacement_string device_or_file
EOF
}

KEY=$1
NEWKEY=$2
DEV=$3

if [[ ${#} != 3 ]]; then
        printf "ERROR: Wrong number of arguments.\n\n"
        help
        exit -2
    fi
done

# make sure that new len(newkey) == len(key)
if [[ ${#KEY} -ne ${#NEWKEY} ]]; then
    echo "Please use equal key lengths"
    exit -1
fi

PLACES=`grep --color=never -aob ${KEY} ${DEV}| sed -r 's/([0-9]+):.*/\1/g'`

for i in ${PLACES}; do
    dd of=${DEV} obs=1 seek=${i} <<< "${NEWKEY}"
done
