#!/bin/bash
# Utility to push to remote git repo. Removes compiled files, changes to another
# repo to allow push and changes back to master afterwards. Requires a remote
# repo "bare".

args=${@}

# Split words at spaces
IFS=' '

# Set the path to the remote git repo. Extract the server URL and the repo path
set $(git config --local --get remote.origin.url | sed -r 's#.*?://(.*?):(.*?)$#\1 \2#')
repo=${1}
path=${2}

cur_branch=$(ssh ${repo} "cd ${path} && git rev-parse --abbrev-ref HEAD")
ssh ${repo} "cd ${path} && git checkout master~ 2>/dev/null"
git ${args}
ssh ${repo} "cd ${path} && git checkout ${cur_branch}"
